### ISSUE TITLE
Cannot read property 'end' of null

### ISSUE THREAD

**Issue by TimWolla** [babel/minify#614]
Babili crashes with the follow stack trace:
```
TypeError: foo.js: Cannot read property 'end' of null
    at _evaluate (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/evaluation.js:159:57)
    at evaluate (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/evaluation.js:65:17)
    at NodePath.evaluate (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/evaluation.js:41:15)
    at isPureAndUndefined (/pwd/node_modules/babel-plugin-transform-remove-undefined/lib/index.js:19:25)
    at PluginPass.ReturnStatement (/pwd/node_modules/babel-plugin-transform-remove-undefined/lib/index.js:138:15)
    at newFn (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/usr/local/share/.config/yarn/global/node_modules/babel-traverse/lib/context.js:150:16)
```

My `.babelrc` is as follows:
```json
{ "presets": [ "es2015",
               "babili"
             ]
}
```

A minimal example that reproduces the error is:
```javascript
function a() {
	var c = 1

	class B {

	}

	return B
}
```

My package.json is:
```json
{
  "dependencies": {
    "babel-preset-env": "^1.5.2",
    "babel-preset-es2015": "^6.24.1",
    "babili": "^0.1.4"
  }
}
```

**Comment by GeoffreyBooth** [comment]
I had this issue too; but for some reason, it went away when I ran Babel twice: the first time with only the `env` preset, the second time with only the `babili` preset. Running Babel with both presets together triggers this error.
