### ISSUE TITLE
Destructuring assignment fails in 0.2 and 0.3 with babel7

### ISSUE THREAD

**Issue by diervo** [babel/minify#802]
#### Input Code

```js
function x() {
    const { method } = $api;
}

```

#### Actual Output
```js
TypeError: undefined: Duplicate declaration "b" (This is an error on an internal node. Probably an internal error.)
    at File.buildCodeFrameError (/x/node_modules/@babel/core/lib/transformation/file/file.js:207:12)
    at Scope.checkBlockScopedCollisions (/x/node_modules/@babel/traverse/lib/scope/index.js:303:27)
    at Scope.registerBinding (/x/node_modules/@babel/traverse/lib/scope/index.js:485:16)
    at Scope.registerDeclaration (/x/node_modules/@babel/traverse/lib/scope/index.js:404:14)
    at Object.BlockScoped (/x/node_modules/@babel/traverse/lib/scope/index.js:146:28)
    at Object.newFn (/x/node_modules/@babel/traverse/lib/visitors.js:266:17)
    at NodePath._call (/x/node_modules/@babel/traverse/lib/path/context.js:64:19)
    at NodePath.call (/x/node_modules/@babel/traverse/lib/path/context.js:34:14)
    at NodePath.visit (/x/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/x/node_modules/@babel/traverse/lib/context.js:135:18)
```

#### Expected Output

```js
function x() {
  var _$api = $api,
    a = _$api.method;
}
```

#### Details
I narrow down the bug to the `babel-plugin-minify-mangle-names` plugin.

This reproduces in preset package 0.2 and 0.3 when using babel `7.0.0-beta.40` (I know is not officially support it yet, but since a trivial example fails, I wonder if there will more of these bugs).

I will try to figure out the root cause and submit a PR, but in the mean time any hints from the owners of the code will be appreciated.

**Comment by boopathi** [comment]
Thanks for trying this out with babel-7.

I'm debugging this right now and fixed the mentioned issue (Duplicate declaration "b"), but after this fix, there is something else that's broken as well. I will fix that and update.

**Comment by diervo** [comment]
@boopathi let me know how I can help, is there a branch I can take a look at?
Once you figure out a fix I can push our own packages to get over the hump.

**Comment by boopathi** [comment]
I'm pushed to the branch: `babel-7`

PR - https://github.com/babel/minify/pull/487

**Comment by diervo** [comment]
Thanks for the quick turnaround will give it a run and report back

**Comment by boopathi** [comment]
babel-7 is merged to master.
