### ISSUE TITLE
Something went wrong when updating

### ISSUE THREAD

**Issue by Cyp** [babel/minify#844]
After updating
```
$ npm update
+ babel-preset-env@1.7.0
+ babel-preset-minify@0.4.2
```
I get
```
~/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Cannot find module '@babel/types' (While processing preset: "~/project/node_modules/babel-preset-minify/lib/index.js")
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/project/node_modules/babel-helper-evaluate-path/lib/index.js:11:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
, and downgrading again doesn't help.

Not sure if it's my configuration that went weird somehow, but I think it should be using `'babel-types'` instead of `'@babel/types'`. Reporting quickly in case it affects everyone updating and not just me.

**Comment by mvberg** [comment]
@Cyp downgrading does not work because [babel-preset-minify](https://github.com/babel/minify/blob/master/packages/babel-preset-minify/package.json#L17-L28) has a `^0.4.2` "version range" in the transitive dependencies, so you'll have to use a package-lock or a npm-shrinkwrap file to force these to the `0.4.0` version

**Comment by jenian** [comment]
A temporary fix is to add a resolution to package.json to force babel-helper-evaluate-path to a previous version:

    "resolutions": {
        "babel-helper-evaluate-path": "0.4.0"
    }
