### ISSUE TITLE
Minification fails when a variable is re-declared

### ISSUE THREAD

**Issue by zacharyscott** [babel/minify#873]
**Describe the bug**

When minifying our code using babel-preset-minify as part of our Maven build, our build fails. This occurs only when minifying certain files.

**To Reproduce**
I took one of the files that was failing to be minified, cut it down to its simplest form, and renamed the variables to be a little clearer. It seems to occur when a variable is declared more than once. The js code below causes a build failure:
```
var myObject= {
    decrypt: function(problemInput) {
        var newVariable = problemInput;
        var problemInput = 'test';
        return problemInput;
    }
};
var x = myObject;
```

**Stack Trace**

```
[ERROR] events.js:183
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]       ^
[ERROR] Error: C:/Users/amizzs0/workspace-git-2/xwebproducts/com.x.y.web/src/main/webapp/js/test.js: scopeTracker.addBinding: Binding "problemInput" already exists. Trying to add "problemInput" again.
[ERROR]     at ScopeTracker.addBinding (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\scope-tracker.js:218:13)
[ERROR]     at Scopable.Object.keys.forEach.name (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\index.js:137:26)
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at Scopable (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\index.js:136:39)
[ERROR]     at bfsTraverse (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\bfs-traverse.js:32:43)
[ERROR]     at Mangler.collect (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\index.js:229:7)
[ERROR]     at Mangler.run (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\index.js:54:12)
[ERROR]     at PluginPass.exit (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-plugin-minify-mangle-names\lib\index.js:526:19)
[ERROR]     at newFn (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-traverse\lib\visitors.js:276:21)
[ERROR]     at NodePath._call (C:\Users\amizzs0\workspace-git-2\xwebproducts\com.x.y.web\node_modules\babel-traverse\lib\path\context.js:76:18)
```

**Configuration**

We are using babel-preset-minify and running babel through a Gulp script.

babelrc:

```
{
  presets: [
		['env', {
			'targets': {
				'browsers': ['> 1%', 'ie >= 11']
			},
			'modules': false
		}], ['minify']
	]
}
```

**Additional context**

I realize that the code could be re-written to avoid re-declaring variables- however, I am dealing with a code base largely composed of undocumented legacy software . I don't really know why the code was written this way, and I'd like to re-write it, but it would be nice to get the benefits of babel and the babel minifier without needing to modify this old code too much right away.

**Comment by boopathi** [comment]
I tried it locally with babel-minify master branch and `@babel/preset-env` with your env configuration and it doesn't happen. I'm closing this issue now. Please comment to reopen if you still face it.
