### ISSUE TITLE
Exceptions in 0.5.0

### ISSUE THREAD

**Issue by rahbari** [babel/minify#913]
After Updating to v0.5.0 I get a lot of errors while minifying single files:

```
TypeError: unknown: Cannot read property 'contexts' of null
    at NodePath._getQueueContexts (D:\WiFiSpot\node_modules\babel-traverse\lib\path\context.js:278:21)
    at NodePath._containerInsert (D:\WiFiSpot\node_modules\babel-traverse\lib\path\modification.js:94:23)
    at NodePath._containerInsertBefore (D:\WiFiSpot\node_modules\babel-traverse\lib\path\modification.js:137:15)
    at NodePath.insertBefore (D:\WiFiSpot\node_modules\babel-traverse\lib\path\modification.js:56:19)
    at NodePath.unshiftContainer (D:\WiFiSpot\node_modules\babel-traverse\lib\path\modification.js:239:15)
    at BuiltInReplacer.replace (D:\WiFiSpot\node_modules\babel-plugin-minify-builtins\lib\index.js:164:22)
    at PluginPass.exit (D:\WiFiSpot\node_modules\babel-plugin-minify-builtins\lib\index.js:205:27)
    at newFn (D:\WiFiSpot\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (D:\WiFiSpot\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (D:\WiFiSpot\node_modules\babel-traverse\lib\path\context.js:48:17)
```

**Comment by JeffML** [comment]
Seeing same issue.  Why was this closed?

**Comment by rv-jbaker** [comment]
We are also seeing this issue. Did you find a resolution @rahbari?

**Comment by rahbari** [comment]
@rv-jbaker @JeffML The problem is babel core and some modules (Not babel minifiy) have new package names and you just don't get new version with npm update, for example:

		"@babel/core": "^7.1.6",
		"@babel/plugin-syntax-object-rest-spread": "^7.0.0",
		"@babel/plugin-transform-modules-commonjs": "^7.1.0",

**Comment by seanmorris** [comment]
I'm having this issue as well.

**Comment by seanmorris** [comment]
Disabling the "builtIn" plugin seems to suppress the error. I'm using brunch so here's my working config:

```
exports.plugins = {
  babel: {
    'presets': ['es2015'],
    'env': {
      'production': {
        'presets': [['minify', {
          'builtIns': false
        }]]
      }
    }
  },
};
```
