### ISSUE TITLE
 Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by mblout** [babel/minify#974]
seeing " Cannot read property 'add' of undefined" with the latest

sample code, *junk.js*

```const y = () => {};
function x(foo = y) {}```

command: *npx babel junk.js --presets=minify*

*package.json*
```{
  "name": "babelbug",
  "version": "1.0.0",
  "description": "",
  "devDependencies": {
    "@babel/core": "^7.7.0",
    "@babel/preset-env": "^7.7.0",
    "@babel/cli": "^7.7.0",
    "babel-preset-minify": "~0.5.0"
  }
}```


stack 
```{ TypeError: C:\babelbug\junk.js: Cannot read property 'add' of undefined
    at ScopeTracker.addReference (C:\babelbug\node_modules\babel-plugin-minify-mangle-names\lib\scope-tracker.js:47:34)
    at ReferencedIdentifier (C:\babelbug\node_modules\babel-plugin-minify-mangle-names\lib\index.js:196:26)
    at newFn (C:\babelbug\node_modules\@babel\traverse\lib\visitors.js:220:17)
    at bfsTraverse (C:\babelbug\node_modules\babel-plugin-minify-mangle-names\lib\bfs-traverse.js:32:43)
    at Mangler.collect (C:\babelbug\node_modules\babel-plugin-minify-mangle-names\lib\index.js:229:7)
    at Mangler.run (C:\babelbug\node_modules\babel-plugin-minify-mangle-names\lib\index.js:54:12)
    at PluginPass.exit (C:\babelbug\node_modules\babel-plugin-minify-mangle-names\lib\index.js:558:19)
    at newFn (C:\babelbug\node_modules\@babel\traverse\lib\visitors.js:179:21)
    at NodePath._call (C:\babelbug\node_modules\@babel\traverse\lib\path\context.js:55:20)
    at NodePath.call (C:\babelbug\node_modules\@babel\traverse\lib\path\context.js:42:17) code: 'BABEL_TRANSFORM_ERROR' }```

**Comment by anthony-quiros** [comment]
I have the same error with this code:
```
  const defaultLib = require('./default-lib');

  foo(lib = defaultLib) {
    this.lib = lib;
  }
```

**Comment by mjakobis** [comment]
The issue seems to be with default functional parameters set to a constant.

**Comment by arantes555** [comment]
Seeing the same problem here... setting `mangle: false` in the options seems to work-around the problem.

**Comment by arantes555** [comment]
Also, seems there is a similar old issue : https://github.com/babel/minify/issues/556

**Comment by somewhatabstract** [comment]
I see the same issue when using `rollup-babel-minify`. Dependabot tried to update to latest babel and couldn't due to this issue.

```
TypeError: unknown: Cannot read property 'add' of undefined
    at ScopeTracker.addReference (/Users/jeffyates/git/checksync/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:47:34)
    at ReferencedIdentifier (/Users/jeffyates/git/checksync/node_modules/babel-plugin-minify-mangle-names/lib/index.js:196:26)
    at newFn (/Users/jeffyates/git/checksync/node_modules/@babel/traverse/lib/visitors.js:220:17)
    at bfsTraverse (/Users/jeffyates/git/checksync/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:32:43)
    at Mangler.collect (/Users/jeffyates/git/checksync/node_modules/babel-plugin-minify-mangle-names/lib/index.js:229:7)
    at Mangler.run (/Users/jeffyates/git/checksync/node_modules/babel-plugin-minify-mangle-names/lib/index.js:54:12)
    at PluginPass.exit (/Users/jeffyates/git/checksync/node_modules/babel-plugin-minify-mangle-names/lib/index.js:558:19)
    at newFn (/Users/jeffyates/git/checksync/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/jeffyates/git/checksync/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/jeffyates/git/checksync/node_modules/@babel/traverse/lib/path/context.js:42:17)
```

**Comment by SalvatorePreviti** [comment]
Same issue here.

**Comment by mnosuk** [comment]
same issue here :(

**Comment by DiegoRBaquero** [comment]
Same issue here to build webtorrent

**Comment by kmweaver** [comment]
I'm having the same issue when I'm assigning a default value to a parameter. As soon as I remove the default value, the issue is gone.

**Comment by monokee** [comment]
Same issue

**Comment by arantes555** [comment]
I have noticed a weird behaviour :
- I have `@babel/core@7.5.5`, and I do not hit this issue
- If I update `@babel/core` to any superior version, I start hitting the issue
- If I then rollback `@babel/core` to `7.5.5`, I *still* hit the issue.

I think this means the issue is caused by one of `@babel/core`'s dependencies. Not sure how to pinpoint which one :/

**Comment by DeividVeloso** [comment]
Same issue here.

**Comment by quitedensepoint** [comment]
I also see this issue. Happens when calculating a default parameter that is set to be the output of a function being exported like such:

`
const myFunction = () => {};

module.exports = (arg = myFunction()) => {};`

I've narrowed it down to something in https://github.com/babel/babel/blob/main/CHANGELOG.md#v745-2019-05-21
Not sure exactly which change in there causes it, but I suspect it has something to do with https://github.com/babel/babel/pull/9998 since that particular change involves optional parameters.

**Comment by alfokaha-taima** [comment]
same issue :(

**Comment by meduzen** [comment]
> The issue seems to be with default functional parameters set to a constant.

Same for me on both babel-preset-minify 0.4.3 and 0.5.1.

This doesn’t compile:

```js
import { doc } from '../utils/Document';

const DEFAULT_DEBOUNCE_DELAY = 100

let resizeTimer = null

export default function debounceResize(callback, delay = DEFAULT_DEBOUNCE_DELAY) {
  clearTimeout(resizeTimer)
  doc.classList.add('resizing')

  resizeTimer = setTimeout(() => {
    doc.classList.remove('resizing')
    callback()
  }, delay)
}

```

<details>
<summary>Stack trace:</summary>

```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
    TypeError: /resources/js/events/resize.js: Cannot read property 'add' of undefined
        at ScopeTracker.addReference (/node_modules/babel-plugin-minify-mangle-names/lib/scope-tracker.js:47:34)
        at ReferencedIdentifier (/node_modules/babel-plugin-minify-mangle-names/lib/index.js:196:26)
        at newFn (/node_modules/@babel/traverse/lib/visitors.js:216:17)
        at bfsTraverse (/node_modules/babel-plugin-minify-mangle-names/lib/bfs-traverse.js:32:43)
        at Mangler.collect (/node_modules/babel-plugin-minify-mangle-names/lib/index.js:229:7)
        at Mangler.run (/node_modules/babel-plugin-minify-mangle-names/lib/index.js:54:12)
        at PluginPass.exit (/node_modules/babel-plugin-minify-mangle-names/lib/index.js:526:19)
        at newFn (/node_modules/@babel/traverse/lib/visitors.js:175:21)
        at NodePath._call (/node_modules/@babel/traverse/lib/path/context.js:55:20)
        at NodePath.call (/node_modules/@babel/traverse/lib/path/context.js:42:17)
        at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:101:8)
        at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:112:16)
        at TraversalContext.visitSingle (/node_modules/@babel/traverse/lib/context.js:84:19)
        at TraversalContext.visit (/node_modules/@babel/traverse/lib/context.js:140:19)
        at Function.traverse.node (/node_modules/@babel/traverse/lib/index.js:82:17)
        at traverse (/node_modules/@babel/traverse/lib/index.js:64:12)
        at transformFile (/node_modules/@babel/core/lib/transformation/index.js:107:29)
        at transformFile.next (<anonymous>)
        at run (/node_modules/@babel/core/lib/transformation/index.js:35:12)
        at run.next (<anonymous>)
        at Function.transform (/node_modules/@babel/core/lib/transform.js:27:41)
        at transform.next (<anonymous>)
        at step (/node_modules/gensync/index.js:254:32)
        at /node_modules/gensync/index.js:266:13
        at async.call.result.err.err (/node_modules/gensync/index.js:216:11)
     @ ./resources/js/events/index.js 1:89-126 1:217-231
     @ ./resources/js/app.js
```
</details>


This compiles properly:

```js
import { doc } from '../utils/Document';

let resizeTimer = null

export default function debounceResize(callback, delay = 100) {
  clearTimeout(resizeTimer)
  doc.classList.add('resizing')

  resizeTimer = setTimeout(() => {
    doc.classList.remove('resizing')
    callback()
  }, delay)
}

```

**Comment by arantes555** [comment]
I'm still stuck on @babel/core@7.5.5 because of this. Any way we can help fix this ?

**Comment by s100** [comment]
I was able to work around this problem by using [`@babel/plugin-transform-parameters`](https://babeljs.io/docs/en/babel-plugin-transform-parameters) to transpile away the default parameters syntax prior to minification. I would still be interested to see the bug fixed though.

**Comment by fwextensions** [comment]
I was seeing the same thing as @arantes555, where upgrading to the latest package started causing the issue, but rolling back to the previously working version still produced the bug, even after wiping and reinstalling `node_modules`.  I eventually gave up and switched to [terser](https://terser.org/), which has been working fine.

**Comment by arantes555** [comment]
@fwextensions I ended up switching to terser too...

For those who, for some reason, cannot switch, the trick in this case is to wipe node_modules, and roll-back both your package.json **and pacakge-lock.json**, then re-installing.

**Comment by ruymaster** [comment]
I got same error.

**Comment by dhlolo** [comment]
Any update? Seem there is an PR checked but not merged.

**Comment by TiagoSilvaPereira** [comment]
> I was able to work around this problem by using [`@babel/plugin-transform-parameters`](https://babeljs.io/docs/en/babel-plugin-transform-parameters) to transpile away the default parameters syntax prior to minification. I would still be interested to see the bug fixed though.

Confirming it works with **@babel/plugin-transform-parameters** Thank you very much @s100

**Comment by ochodek** [comment]
Any update? I found that it started to fail after a change in `@babel/types@7.8.0` - https://github.com/babel/babel/pull/10917
Hopefuly https://github.com/babel/minify/pull/1024 will be merged soon.

**Comment by jamonholmgren** [comment]
@ochodek I used Yarn's built-in `yarn patch` feature to apply #1024's changes (if you're not using Yarn 3+, you can use patch-package instead). It fixed the issue for me.
