### ISSUE TITLE
babel-plugin-minify-constant-folding fails on var split = ''.split;

### ISSUE THREAD

**Issue by yuri-karadzhov** [babel/minify#986]
`babel-plugin-minify-constant-folding` fails on expression
```js
var split = ''.split;
```

**To Reproduce**

Minimal code to reproduce the bug

```js
var split = ''.split;
```

**Stack Trace**

```
Error: /node_modules/core-js/internals/indexed-object.js: don't know how to turn this value into a node
      at Object.valueToNode (/Users/yuri/web/hq/node_modules/@babel/types/lib/converters/valueToNode.js:87:9)
      at PluginPass.Expression (/Users/yuri/web/hq/node_modules/babel-plugin-minify-constant-folding/lib/index.js:195:26)
      at PluginPass.newFn (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/visitors.js:220:17)
      at newFn (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/visitors.js:179:21)
      at NodePath._call (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/path/context.js:42:17)
      at NodePath.visit (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/path/context.js:90:31)
      at TraversalContext.visitQueue (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/context.js:112:16)
      at TraversalContext.visitSingle (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/context.js:84:19)
      at TraversalContext.visit (/Users/yuri/web/hq/node_modules/@babel/traverse/lib/context.js:140:19)
```

**Configuration**

How are you using babel-minify?

`babel-preset-minify trough babel API`

babel-minify version: `0.5.1`

babel version : `7.9.0`

babel-minify-config:

```json5
{
  builtIns: false,
  deadcode: false,
  // evaluate: false, // Switching babel-plugin-minify-constant-folding off solves the problem
  mangle: false,
}
```

**Comment by clarle** [comment]
I'm unable to reproduce this with `0.5.1` and latest stable Babel as of this writing (`7.11.1`).  

@yuri-karadzhov Do you still see the issue today, and can you give me the specific command you're running if so?

**Comment by hqjs** [comment]
Checked it works with latest babel `7.11.1` indeed.

**Comment by hqjs** [comment]
@clarle Can you please reopen the issue as it still fails in this [minimal example](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBBAOAbAlrAvDA5JgdAlUA3AFDH6o7ACGiiAFNgDRaYCUJQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.11.6&externalPlugins=babel-plugin-minify-constant-folding%400.5.0)
```js
const split = ''.split;
split.call('', '');
```
with the same error `don't know how to turn this value into a node`.
